name: m1-math
channels:
  - defaults
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python
  - openblas
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - pytorch
  - scikit-learn
  - torchvision
  - opencv
  - datasets
  - tqdm
  - ipywidgets
  - tensorboardX
  - pip
  - pip: # This change was made because the moe_lm models were not in the latest release of fairseq, but rather the main branch
      - git+https://github.com/huggingface/transformers
variables: # for macOSX only
  CFLAGS: -stdlib=libc++ #https://github.com/pytorch/fairseq/#requirements-and-installation
