name: m1-math
channels:
  - defaults
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python
  - openblas
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - pytorch
  - scikit-learn
  - torchvision
  - opencv
  - datasets
  - transformers
  - tqdm
  - fairseq